# This is the main configuration file for the Spigot.
# Modify with extreme caution, and make sure you know what you are doing.

knockback:
  current: default
  profiles: {}
hide-players-from-tab: true
fire-player-move-event: false
fire-left-click-air: false
fire-left-click-block: false
entity-activation: false
invalid-arm-animation-kick: false
mob-ai: true
1-8-enabled: false
do-chunk-unload: true
block-operations: false
