# KitPvP - 1.0

# ** Messages **
No-Permissions-Message: "&d&lKitPvP &7┃ &cYou do not have permissions"
Reloaded-Message: "&d&lKitPvP &7┃ &fKitPvP has been reloaded."
OnBlockPlace-Message: "&d&lKitPvP &7┃ &7&oYou have build mode disabled."
OnBlockBreak-Message: "&d&lKitPvP &7┃ &7&oYou have build mode disabled."
Build-Enabled-Message: "&d&lKitPvP &7┃ &fYou have &aenabled &fbuild mode."
Build-Disabled-Message: "&d&lKitPvP &7┃ &fYou have &cdisabled &fbuild mode."
Player-Only-Message: "&cConsole may not use this command."

# ** Join Messages **
# (DOES NOT SUPPORT PLACEHOLDERAPI)
join-events:
  sound-enabled: true
  messages:
    - ""
    - "&fYou're now connected to our &d&lKitPvP &fserver"
    - "&7&oThe map began on the 1st of December."
    - ""

# ** Kill rewards **
# (DOES NOT SUPPORT PLACEHOLDERAPI)
kd-events:
  kill-sound-enabled: true
  xp-amount: 3
  death-message: "&e{VICTIM} &chas died"
  kill-message: "&e{KILLER} &chas killed &e{VICTIM}"
  commands:
    - crate key {KILLER} Kill 1
    - eco give {KILLER} 100
    - eco TAKE {VICTIM} 50
  killer-messages:
  - "&d&lKitPvP &7┃ &aYou have been given 100$ for killing {VICTIM}"
  victim-messages:
  - "&d&lKitPvP &7┃ &dYou have lost 50$ for dying to {KILLER}"

# ** Stats **
# (DOES NOT SUPPORT PLACEHOLDERAPI)
stats:
  message:
    - "&7&m---------------------------"
    - "&d&lStatistics"
    - " &fKills&7: &d{KILLS}"
    - " &fDeaths&7: &d{DEATHS}"
    - "&7&m---------------------------"

stats-other:
  message:
    - "&7&m---------------------------"
    - "&d&l{PLAYER}'s &d&lStatistics"
    - " &fKills&7: &d{KILLS}"
    - " &fDeaths&7: &d{DEATHS}"
    - "&7&m---------------------------"

# ** Scoreboard **
# (SUPPORTS PLACEHOLDERAPI)
Scoreboard:
  Title: "&d&lServer &7┃ &fKitPvP"
  Default:
    - "&7&m-------------------------"
    - "&fRank: &r%aqua_player_rank%"
    - "&fBalance: &d%vault_eco_balance_fixed%$"
    - "&fKills: &d%statistic_player_kills%"
    - "&fDeaths: &d%statistic_deaths%"
    - "&7&m-------------------------"
    - "&fTeam: &d%betterTeams_name%"
    - "&7&m-------------------------"

# ** Help UI **
# (DOES NOT SUPPORT PLACEHOLDERAPI)
helpui:
  size: 27
  title: "&dKitPvP &8┃ &fHelp"
  kitpvp:
    item: "BOOK"
    itemposition: 11
    title: '&dKitPvP Commands'
    lore:
      - ''
      - '&8* &d/kit &8&m-&f Select a kit to fight with through a gui.'
      - '&8* &d/kit <name> &8&m-&f Select a specific kit.'
      - '&8* &d/crate &8&m-&f Exchange virtual keys for physical keys.'
      - '&8* &d/pv <number> &8&m-&f Access your vault, store your items.'
      - '&8* &cMore in development.'
      - ''
  howplay:
    item: "BOOK"
    itemposition: 13
    title: '&dHow to play'
    lore:
      - ''
      - ' &fThe aim of the server is to fight with other players, to gain kill keys'
      - ' &fabilities, more & progress through the server!'
      - ''
  economy:
    item: "BOOK"
    itemposition: 15
    title: '&dEconomy Commands'
    lore:
      - ''
      - '&8* &d/bal &8&m-&f See how much money you have.'
      - '&8* &d/money pay <name> &8&m-&f Send other players money.'
      - '&8* &d/money check <name> &8&m-&f See the balance of others'
      - '&8* &d/money top &8&m-&f See the players with the highest balance.'
      - ''
