name: KitPvP
version: 1.0
authors: [Flairings, Pottinqq]
main: me.flairings.kitpvp.Main
description: KitPvP core for UnoPvP.

commands:
  kitpvp:
    description: Help command for KitPvP plugin.
  stats:
    description: Check your kills and deaths statistics.
    aliases:
      - statistics
      - kdr
      - kd
  howtoplay:
    description: How To Play GUI
    aliases:
      - help
      - htp
      - howtonotbeshitatthegame101lol
  build:
    description: Enable and Disable breaking & placing blocks.
    aliases:
      - buildmode
  kitpvp-reload:
    description: Safely reloads the kitpvp core.
  killrewards:
    description: View the current kill reward settings
  profile:
    description: Change a users profile settings

permissions:
  kitpvp.command.helpcommand:
    description: This is the main help command to KitPvP

  kitpvp.helpcommand.howtoplay:
    description: This allows use of the subcommand "/kitpvp helpui"

  kitpvp.helpcommand.stats:
    description: This allows use of the subcommand "/kitpvp stats"

  kitpvp.helpcommand.build:
    description: This allows use of the subcommand "/kitpvp build"

  kitpvp.command.build:
    description: This permission allows the use of /build. find out more about /build with "/kitpvp build"

  kitpvp.helpcommand.reload:
    description: This permission allows the user to reload the kitpvp core.

  kitpvp.command.howtoplay:
    description: This permission allows the user to access the help user interface, find out more about /help with "/kitpvp help"

  kitpvp.command.reload:
    description: This permission allows the user to reload the kitpvp core.

  kitpvp.helpcommand.killrewards:
    description: This permission allows the user to view the current kill reward settings

  kitpvp.command.killrewards:
    description: This permission allows the user to view the current kill reward settings