# KitPvP - 1.0

# ** Prefix **
# {PREFIX}
Prefix: "&d&lUnoPvP &7┃"

# ** Messages **
No-Permissions-Message: "{PREFIX} &cYou do not have permissions"
Reloaded-Message: "{PREFIX} &fKitPvP has been reloaded."
OnBlockPlace-Message: "{PREFIX} &7&oYou have build mode disabled."
OnBlockBreak-Message: "{PREFIX} &7&oYou have build mode disabled."
Build-Enabled-Message: "{PREFIX} &fYou have &aenabled &fbuild mode."
Build-Disabled-Message: "{PREFIX} &fYou have &cdisabled &fbuild mode."
Player-Only-Message: "&cConsole may not use this command."
player-kill-player-message: "&e{KILLER} &chas killed &e{VICTIM}"
death-message: "&e{VICTIM} &chas died"

# ** Join Messages **
join-events:
  sound-enabled: true
  messages:
    - ""
    - "&6You're now connected to our &6&lKitPvP &6server"
    - "&7&oThe map began on the 1st of December."
    - ""

# ** Kill rewards **
kill-rewards:
  sound-enabled: true
  xp-amount: 3
  commands:
    - crate key {PLAYER} Kill 1
    - eco give {PLAYER} 100
  message: "{PREFIX} &aYou have been given 100$ for killing {PLAYER}"

# Placeholders
# {XP}
# {CMDs}
kill-rewards-help:
  message:
    - "&6Current kill reward settings: "
    - "&6XP: &f{XP}"
    - "&6CMDs: &f{CMDs}"


# ** Stats **
# Placeholders
# {Kills}
# {Deaths}
stats:
  message:
    - "&7&m---------------------------"
    - "&d&lStatistics"
    - " &fKills&7: &d{KILLS}"
    - " &fDeaths&7: &d{DEATHS}"
    - "&7&m---------------------------"

stats-other:
  message:
    - "&7&m---------------------------"
    - "&d&l{PLAYER}'s &d&lStatistics"
    - " &fKills&7: &d{KILLS}"
    - " &fDeaths&7: &d{DEATHS}"
    - "&7&m---------------------------"

# ** Help UI **
items:
  kitpvp:
    title: '&dKitPvP Commands'
    lore:
      - ''
      - '&8* &d/kit &8&m-&f Select a kit to fight with through a gui.'
      - '&8* &d/kit <name> &8&m-&f Select a specific kit.'
      - '&8* &d/crate &8&m-&f Exchange virtual keys for physical keys.'
      - '&8* &d/pv <number> &8&m-&f Access your vault, store your items.'
      - '&8* &cMore in development.'
      - ''
  howplay:
    title: '&dHow to play'
    lore:
      - ''
      - ' &fThe aim of the server is to fight with other players, to gain kill keys'
      - ' &fabilities, more & progress through the server!'
      - ''
  economy:
    title: '&dEconomy Commands'
    lore:
      - ''
      - '&8* &d/bal &8&m-&f See how much money you have.'
      - '&8* &d/money pay <name> &8&m-&f Send other players money.'
      - '&8* &d/money check <name> &8&m-&f See the balance of others'
      - '&8* &d/money top &8&m-&f See the players with the highest balance.'
      - ''

# ** Scoreboard **

# Placeholders
# {RANK} - Aquacore Rank name with color
# {KILLS} - Bukkit Statistic (Player_Kills)
# {DEATHS} - Bukkit Statistic (Deaths)
# {BALANCE} - Vault Balance
# {TEAM} - Better-Teams team name

Scoreboard:
  Default:
    - "&7&m-------------------------"
    - "&fRank: &r%aqua_player_rank%"
    - "&fKills: &d%statistic_player_kills%"
    - "&fDeaths: &d%statistic_deaths%"
    - "&fBalance: &d%vault_eco_balance_fixed%$"
    - "&7&m-------------------------"
    - "&fTeam: &d%betterTeams_name%"
    - "&7&m-------------------------"
